# Generated by Django 5.0.6 on 2024-06-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_grade_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='class_id',
            new_name='class_s',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='class_s',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
